name: Build, Test, and Analyze with SonarCloud

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: Check if package.json exists
        id: check_package
        run: |
          if [ -f package.json ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check_package.outputs.exists == 'true'
        run: npm install

      - name: Run tests with coverage
        if: steps.check_package.outputs.exists == 'true'
        run: npm run test -- --coverage
        env:
          CI: true

      - name: SonarCloud Scan
        if: steps.check_package.outputs.exists == 'true'
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
